export const rootPaths = {
  homeRoot: '',
  usersRoot: 'users',
  labelsRoot: 'labels',
  newslettersRoot: 'newsletters',
  subscriptionSalesRoot: 'subscription-sales',
  subscribersRoot: 'subscribers',
  userDistributionsRoot: 'user-distributions',
  settingsRoot: 'settings',
  pagesRoot: 'pages',

  applicationsRoot: 'applications',
  ecommerceRoot: 'ecommerce',
  authRoot: 'authentication',
  notificationsRoot: 'notifications',
  calendarRoot: 'calendar',
  messageRoot: 'messages',
  errorRoot: 'error',
};

export default {
  home: `/${rootPaths.homeRoot}`,
  users: `/${rootPaths.usersRoot}`,
  labels: `/${rootPaths.labelsRoot}`,
  newsletters: `/${rootPaths.newslettersRoot}`,
  subscriptionSales: `/${rootPaths.subscriptionSalesRoot}`,
  subscribers: `/${rootPaths.subscribersRoot}`,
  userDistributions: `/${rootPaths.userDistributionsRoot}`,
  settings: `/${rootPaths.settingsRoot}`,
  login: `/${rootPaths.authRoot}/login`,
  signup: `/${rootPaths.authRoot}/sign-up`,
  resetPassword: `/${rootPaths.authRoot}/reset-password`,
  forgotPassword: `/${rootPaths.authRoot}/forgot-password`,
  404: `/${rootPaths.errorRoot}/404`,
};
